pull_request_rules:
  - name: Automatic merge for Owner
    conditions:
      - author=matejkosiarcik
      - status-success=stickler-ci
      - status-success=continuous-integration/travis-ci/pr
      - base=master
    actions:
      merge:
        method: merge
        strict: true
  - name: Automatic merge for collaborators
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=stickler-ci
      - status-success=continuous-integration/travis-ci/pr
      - base=master
    actions:
      merge:
        method: merge
        strict: true
