repeating_rules: &repeating_rules
  - status-success=continuous-integration/travis-ci/pr
  - status-success=stickler-ci
  - base=master

actions: &repeating_actions
  merge:
    method: merge
    strict: true

pull_request_rules:
  - name: Automatic merge for Owner
    conditions: <<: *repeating_rules
      - author=matejkosiarcik
    actions: *repeating_actions
  - name: Automatic merge for collaborators
    conditions: <<: *repeating_rules
      - "#approved-reviews-by>=1"
    actions: *repeating_actions
