pull_request_rules:
  - name: Automatic merge for Owner
    conditions:
      - author=matejkosiarcik
      - status-success=stickler-ci
      - status-success=continuous-integration/travis-ci/pr
      - status-success=ci/circleci
      - base=master
    actions:
      merge:
        method: merge
        strict: true
