pull_request_rules:
  - name: Automatic Merge (for Owner)
    conditions:
      - author=matejkosiarcik
      - base=master
      - label!=work-in-progress
      - status-success=stickler-ci
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
      - status-success=test # circle-ci
    actions:
      merge:
        method: merge
        strict: smart
