language: generic

os:
  - linux
  - osx

addons:
  apt:
    update: true
    packages:
      - python3
      - python3-pip
      - python3-venv
      - python3-setuptools
      - upx
  homebrew:
    update: true
    brewfile: true

matrix:
  fast_finish: true

install: skip

before_script:
  - uname -a
  - if [ "${TRAVIS_OS_NAME}" = 'osx' ]; then sw_vers; fi

script:
  - make
