language: generic

os:
  - linux
  - osx

addons:
  apt:
    update: true
    packages:
      - bats
  homebrew:
    update: true
    packages:
      - bats-core
      - duti

matrix:
  fast_finish: true

install: skip

before_script:
  - uname -a
  - sw_vers

script:
  - bats 'test.bats'
  - sh home/install.sh
  - sh setup/install.sh
  - sh bin/install.sh
