language: generic

os:
  - linux
  - osx

addons:
  apt:
    update: true
    packages:
      - zsh
  homebrew:
    update: true
    brewfile: true

matrix:
  fast_finish: true

  include:
    - &apt-test
      sudo: true
      install: skip
      script: sed -E 's~(\s*)#(.*)~~' <'dependencies/apt/apt.txt' | grep -vE '^(\s*)$' | xargs -tn1 apt-get install -y
    - <<: *apt-test
      dist: precise
    - <<: *apt-test
      dist: trusty
    - <<: *apt-test
      dist: xenial
    - <<: *apt-test
      dist: bionic

    - &gem-test
      language: ruby
      install: skip
      script: sh 'dependencies/gem/install.sh'
    - <<: *gem-test
      os: osx
      if: branch = master

    - &npm-test
      language: node_js
      install: skip
      script: node 'dependencies/npm/install.js'
    - <<: *npm-test
      os: osx
      if: branch = master
    - <<: *npm-test
      os: windows
      node_js: node

    - &pip-test
      language: python
      install: skip
      script: pip install -r 'dependencies/pip/requirements.txt'
    - <<: *pip-test
      os: osx
      language: generic
      if: branch = master

install: skip

before_script:
  - uname -a
  - if [ "${TRAVIS_OS_NAME}" = 'osx' ]; then sw_vers; fi

script:
  - sh 'home/install.sh'
  - sh 'setup/install.sh'
