language: generic

os:
  - linux
  - osx

addons:
  apt:
    update: true
    packages:
      - python3
      - python3-pip
      - python3-venv
      - python3-setuptools
  homebrew:
    update: true
    brewfile: true

matrix:
  fast_finish: true
  include:
    - { os: linux, dist: focal, if: branch == master }
    - { os: linux, dist: bionic, if: branch == master }
    - { os: linux, dist: xenial, if: branch == master }
    - { os: osx, osx_image: xcode12, if: branch == master }
    - { os: osx, osx_image: xcode11, if: branch == master }
    - { os: osx, osx_image: xcode10, if: branch == master }

install: skip

script:
  - make
