language: generic

os:
  - linux
  - osx

addons:
  apt:
    update: true
    packages:
      - zsh
  homebrew:
    update: true
    packages:
      - bats-core
      - duti
      - node
      - python
      - ruby
      - zsh

matrix:
  fast_finish: true

  include:
    - &apt-test
      sudo: true
      script: sh 'dependencies/apt/install.sh'
    - <<: *apt-test
      dist: precise
    - <<: *apt-test
      dist: trusty
    - <<: *apt-test
      dist: xenial
    - <<: *apt-test
      dist: bionic

    - &gem-test
      language: ruby
      script: sh 'dependencies/gem/install.sh'
    - <<: *gem-test
      os: osx
      language: generic

    - &npm-test
      language: node
      script: sh 'dependencies/npm/install.sh'
    - <<: *npm-test
      os: osx
      language: node
    - <<: *npm-test
      os: osx
      language: generic

    - &pip-test
      language: python
      script: sh 'dependencies/pip/install.sh'
    - <<: *pip-test
      os: osx
      language: generic

install:
  - |
    if [ "${TRAVIS_OS_NAME}" = 'linux' ] && [ "${TRAVIS_LANGUAGE}" = 'generic' ]; then
      npm install -g bats bats-support bats-assert
    fi

before_script:
  - uname -a
  - |
    if [ "${TRAVIS_OS_NAME}" = 'osx' ]; then
      sw_vers
    fi

script:
  - bats 'tests/main.bats'
  - bats 'tests/zsh.bats'
  - sh 'home/install.sh'
  - sh 'setup/install.sh'
  - sh 'bin/install.sh'
