language: generic

os:
  - linux

addons:
  apt:
    update: true
    packages:
      - python3
      - python3-pip
      - python3-venv
      - python3-setuptools
  homebrew:
    update: true
    brewfile: true

matrix:
  fast_finish: true
  include:
    - { os: osx, if: branch == master }

install: skip

script:
  - make
