language: generic

os:
  - linux
  - osx

addons:
  apt:
    update: true
    packages:
      - zsh
  homebrew:
    update: true
    packages:
      - bats-core
      - duti
      - zsh

matrix:
  fast_finish: true

install:
  - |
    if [ "${TRAVIS_OS_NAME}" = 'linux' ]; then
      npm install -g bats
    fi

before_script:
  - uname -a
  - |
    if [ "${TRAVIS_OS_NAME}" = 'osx' ]; then
      sw_vers
    fi

script:
  - bats 'tests/main.bats'
  - bats 'tests/zsh.bats'
  - sh home/install.sh
  - sh setup/install.sh
  - sh bin/install.sh
