language: generic

os:
  - linux
  - osx

osx_image:
  -
  - xcode10.2

addons:
  apt:
    update: true
  homebrew:
    update: true

matrix:
  fast_finish: true

install: skip

before_script:
  - uname -a

script:
  - sh home/install.sh
  - source ~/.custom.bash
  - sh setup/install.sh
  # - sh dependencies/install.sh
  - sh bin/install.sh
  # - sh default-apps/install.sh
