language: generic

os:
  - linux
  - osx

addons:
  apt:
    update: true
    packages:
      - zsh
  homebrew:
    update: true
    packages:
      - duti
      - node
      - python
      - ruby
      - zsh

matrix:
  fast_finish: true

  include:
    - &apt-test
      sudo: true
      script: sh 'dependencies/apt/install.sh'
    - <<: *apt-test
      dist: precise
    - <<: *apt-test
      dist: trusty
    - <<: *apt-test
      dist: xenial
    - <<: *apt-test
      dist: bionic

    - &gem-test
      language: ruby
      script: sh 'dependencies/gem/install.sh'
    - <<: *gem-test
      os: osx
      only: branch = master

    - &npm-test
      language: node_js
      script: sh 'dependencies/npm/install.sh'
    - <<: *npm-test
      os: osx
      only: branch = master
    - <<: *npm-test
      os: windows
      node_js: node

    - &pip-test
      language: python
      script: sh 'dependencies/pip/install.sh'
    - <<: *pip-test
      os: osx
      language: generic
      only: branch = master

install:
  - |
    if [ "${TRAVIS_LANGUAGE}" = 'generic' ] || [ "${TRAVIS_LANGUAGE}" = 'shell' ]; then
      npm install -g bats
    fi

before_script:
  - uname -a
  - |
    if [ "${TRAVIS_OS_NAME}" = 'osx' ]; then
      sw_vers
    fi

script:
  - bats 'tests/main.bats'
  - bats 'tests/zsh.bats'
  - sh 'home/install.sh'
  - sh 'setup/install.sh'
  - sh 'bin/install.sh'
