language: generic
sudo: false

addons:
  apt:
    update: true
  homebrew:
    update: true
    brewfile: dependencies/Brewfile

matrix:
  fast_finish: true

install: []

before_script:
  - uname -a

script:
  - source "home/shell/custom.sh"
  - source "home/shell/custom.bash"
