language: generic

os:
  - linux
  - osx

addons:
  apt:
    update: true
    packages:
      - zsh
  homebrew:
    update: true
    packages:
      - bats-core
      - duti
      - node
      - python
      - ruby
      - zsh

matrix:
  fast_finish: true

  include:
    - &apt-test
      sudo: true
      script: |
        cd 'dependencies'
        cat 'apt.txt' | while IFS= read package; do sudo apt install "${package}"; done
    - <<: *apt-test
      dist: precise
    - <<: *apt-test
      dist: trusty
    - <<: *apt-test
      dist: xenial
    - <<: *apt-test
      dist: bionic

    - &gem-test
      language: ruby
      script: |
        cd 'dependencies'
        bundle install --system
    - <<: *gem-test
      os: osx
      language: generic

    - &npm-test
      language: node
      script: |
        cd 'dependencies'
        cat 'npm.txt' | while IFS= read package; do npm install "${package}"; done
    - <<: *npm-test
      os: osx
      language: node
    - <<: *npm-test
      os: osx
      language: generic

    - &pip-test
      language: python
      script: |
        cd 'dependencies'
        pip install -r 'requirements.txt'
    - <<: *pip-test
      os: osx
      language: generic

    - &brew-test
      os: osx
      language: generic
      env: file=Brewfile.taps
      script: brew bundle --file="dependencies/brew/${file}"
    - <<: *brew-test
      env: file=Brewfile.browsers
    - <<: *brew-test
      env: file=Brewfile.graphics
    - <<: *brew-test
      env: file=Brewfile.media
    - <<: *brew-test
      env: file=Brewfile.social
    - <<: *brew-test
      env: file=Brewfile.vm

install:
  - |
    if [ "${TRAVIS_OS_NAME}" = 'linux' ] && [ "${TRAVIS_LANGUAGE}" = 'generic' ]; then
      npm install -g bats
    fi

before_script:
  - uname -a
  - |
    if [ "${TRAVIS_OS_NAME}" = 'osx' ]; then
      sw_vers
    fi

script:
  - bats 'tests/main.bats'
  - bats 'tests/zsh.bats'
  - sh home/install.sh
  - sh setup/install.sh
  - sh bin/install.sh
