language: generic
sudo: false

addons:
  apt:
    update: true
  homebrew:
    update: true
    brewfile: dependencies/Brewfile

matrix:
  fast_finish: true

install: []

before_script:
  - uname -a

script:
  - sh home/install.sh
  - source ~/.custom.bash
  - sh setup/install.sh
  # - sh dependencies/install.sh
  - sh bin/install.sh
  # - sh default-apps/install.sh
