language: generic

os:
  - linux
  - osx

addons:
  apt:
    update: true
  homebrew:
    update: true
    brewfile: true

matrix:
  fast_finish: true

  include:
    - &gem-test
      language: ruby
      install: skip
      script: sh 'dependencies/gem/install.sh'
    - <<: *gem-test
      os: osx
      if: branch = master

    - &npm-test
      language: node_js
      node_js: node
      install: skip
      script: node 'dependencies/npm/install.js' local
    - <<: *npm-test
      os: osx
      if: branch = master
    - <<: *npm-test
      os: windows

    - &pip-test
      language: python
      install: skip
      script: pip install -r 'dependencies/pip/requirements.txt'
    - <<: *pip-test
      os: osx
      language: generic
      if: branch = master

install: skip

before_script:
  - uname -a
  - if [ "${TRAVIS_OS_NAME}" = 'osx' ]; then sw_vers; fi

script:
  - sh 'home/install.sh'
  - sh 'setup/install.sh'
