language: generic

os:
  - linux
  - osx

addons:
  apt:
    update: true
  homebrew:
    update: true
    brewfile: true

matrix:
  fast_finish: true

install: skip

before_script:
  - uname -a
  - if [ "${TRAVIS_OS_NAME}" = 'osx' ]; then sw_vers; fi

script:
  - sh 'home/install.sh'
  - sh 'setup/install.sh'
