pull_request_rules:
  - name: Automatic Merge (for Owner)
    conditions:
      - author=matejkosiarcik
      - base=master
      - label!=work-in-progress
      - status-success=stickler-ci
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
      - status-success=test  # circle-ci
      - status-success=Shippable
    actions:
      merge:
        method: merge
        strict: smart

  - name: Remove merged branches (for Owner)
    conditions:
      - author=matejkosiarcik
      - merged
      - base=master
      - head~=^(develop|feature-.+)$
    actions:
      delete_head_branch: {}

  - name: Add WIP label
    conditions:
      - title~=^(wip|WIP).*
    actions:
      label:
        add:
          - work-in-progress

  - name: Automatic merge for dependabot
    conditions:
      - author=dependabot[bot]
      - base=master
      - status-success=stickler-ci
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
      - status-success=test  # circle-ci
      - status-success=Shippable
    actions:
      merge:
        method: rebase
        strict: smart
