version: 2.1

commands:
  env_info:
    steps:
      - run:
        name: Print env info
        command: |
          uname -a
          sw_vers
  install:
    steps:
      - run:
        name: Install dependencies
        command: npm install -g bats
  test:
    steps:
      - run:
          name: Execute tests
          command: bats 'test.bats'
  all:
    steps:
      - checkout
      - env_info
      - install
      - test

workflows:
  version: 2
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - all
