version: 2.1

commands:
  env_info:
    steps:
      - run:
          name: Print env info
          command: uname -a

workflows:
  version: 2
  test:
    jobs:
      - node
      - node-latest
      - node-10
      - node-9
      - node-8
      - bats
      - bats-latest
      - bats-1
      - zsh
      - zsh-latest
      - bash
      - bash-latest
      - bash-5
      - bash-4
      - bash-3
      - python
      - python-latest
      - python-3
      - python-35
      - python-36
      - python-37
      - ruby
      - ruby-latest
      - ruby-2
      - ruby-24
      - ruby-25
      - ruby-26

jobs:
  node: &node
    docker:
      - image: circleci/node
    steps:
      - checkout
      - env_info
      - run: |
          node --version
          npm --version
      - run: npm install bats
      - run: PATH="${PATH}:$(npm bin)" sh -c 'npx --version'
      - run: PATH="${PATH}:$(npm bin)" sh -c 'npx bats --version'
      - run: PATH="${PATH}:$(npm bin)" sh -c 'npx bats "tests/main.bats"'
      - run: cat 'dependencies/npm/npm.txt' | grep -vo '#' | xargs -n1 npm install
  node-latest: { <<: *node, docker: [ image: circleci/node:latest ] }
  node-10: { <<: *node, docker: [ image: circleci/node:10 ] }
  node-9: { <<: *node, docker: [ image: circleci/node:9 ] }
  node-8: { <<: *node, docker: [ image: circleci/node:8 ] }

  bats: &bats
    docker:
      - image: bats/bats
    steps:
      - checkout
      - env_info
      - run: bats --version
      - run: bats 'tests/main.bats'
  bats-latest: { <<: *bats, docker: [ image: bats/bats:latest ] }
  bats-1: { <<: *bats, docker: [ image: bats/bats:1 ] }

  zsh: &zsh
    docker:
      - image: zshusers/zsh
    steps:
      - checkout
      - env_info
      - run: zsh --version
      - run: zsh -c 'source home/shell/custom.zsh'
  zsh-latest: { <<: *zsh, docker: [ image: zshusers/zsh:latest ] }

  bash: &bash
    docker:
      - image: bash
    steps:
      - checkout
      - env_info
      - run: bash --version
      - run: bash -c 'source home/shell/custom.bash'
      - run: sh 'dependencies/apt/install.sh'
  bash-latest: { <<: *bash, docker: [ image: bash:latest ] }
  bash-5: { <<: *bash, docker: [ image: bash:5 ] }
  bash-4: { <<: *bash, docker: [ image: bash:4 ] }
  bash-3: { <<: *bash, docker: [ image: bash:3 ] }

  python: &python
    docker:
      - image: circleci/python
    steps:
      - checkout
      - env_info
      - run: |
          python --version
          pip --version
      - run: pip install --user -r 'dependencies/pip/requirements.txt'
  python-latest: { <<: *python, docker: [ image: circleci/python:latest ] }
  python-3: { <<: *python, docker: [ image: circleci/python:3 ] }
  python-35: { <<: *python, docker: [ image: circleci/python:3.5 ] }
  python-36: { <<: *python, docker: [ image: circleci/python:3.6 ] }
  python-37: { <<: *python, docker: [ image: circleci/python:3.7 ] }

  ruby: &ruby
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - env_info
      - run: |
          ruby --version
          gem --version
          bundle --version
      - run: sh 'dependencies/gem/install.sh'
  ruby-latest: { <<: *ruby, docker: [ image: circleci/ruby:latest ] }
  ruby-2: { <<: *ruby, docker: [ image: circleci/ruby:2 ] }
  ruby-24: { <<: *ruby, docker: [ image: circleci/ruby:2.4 ] }
  ruby-25: { <<: *ruby, docker: [ image: circleci/ruby:2.5 ] }
  ruby-26: { <<: *ruby, docker: [ image: circleci/ruby:2.6 ] }
