version: 2.1

commands:
  install-system-packages:
    steps:
      - run:
          name: Install system packages
          command: |
            if command -v yum >/dev/null 2>&1 && ! command -v dnf >/dev/null 2>&1; then
              yum install -y dnf;
            fi

            if command -v apt-get >/dev/null 2>&1; then
              apt-get update;
              apt-get install --yes python3 python3-pip python3-venv python3-setuptools;
            elif command -v apk >/dev/null 2>&1; then
              apk update --no-cache;
              apk add --no-cache make python3 python3-dev py3-virtualenv;
            elif command -v dnf >/dev/null 2>&1; then
              dnf upgrade -y;
              dnf install -y make python3 python3-pip python3-setuptools;
            elif command -v pacman >/dev/null 2>&1; then
              pacman --noconfirm -Suy python python-pip make;
            elif command -v swupd >/dev/null 2>&1; then
              swupd update;
              swupd bundle-add python-basic make;
            elif command -v zypper >/dev/null 2>&1; then
              zypper --non-interactive update;
              zypper --non-interactive install python3 make
            fi

workflows:
  version: 2
  test:
    jobs:
      - azlint
      - lint
      - linux:
          matrix:
            parameters:
              image:
                - debian:stable
                - ubuntu
                - ubuntu:rolling
                - elementary/docker:stable
                - alpine
                - fedora
                - centos
                - clearlinux
                - opensuse/tumbleweed
                - opensuse/leap
                # - archlinux

jobs:
  azlint:
    docker:
      - image: matejkosiarcik/azlint
    steps:
      - checkout
      - setup_remote_docker
      - run: azlint

  lint:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run: npm ci && npm run lint

  linux:
    parameters:
      image:
        type: string
    docker:
      - image: "<< parameters.image >>"
    steps:
      - checkout
      - install-system-packages
      - run: make
