version: 2.1

commands:
  env_info:
    steps:
      - run:
          name: Print env info
          command: uname -a

workflows:
  version: 2
  test:
    jobs:
      - config-zsh
      - config-bash
      - dependencies
      # TODO: add mac job

jobs:
  config-zsh:
    docker:
      - image: zshusers/zsh
    steps:
      - checkout
      - env_info
      - run: zsh --version
      - run: |
          zsh 'home/install.sh'
          zsh 'setup/install.sh'

  config-bash:
    docker:
      - image: bash
    steps:
      - checkout
      - env_info
      - run: bash --version
      - run: |
          bash 'home/install.sh'
          bash 'setup/install.sh'

  dependencies:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - env_info
      - run: sh 'dependencies/install.sh'
