version: 2.1

commands:
  env_info:
    steps:
      - run:
          name: Print env info
          command: uname -a

workflows:
  version: 2
  test:
    jobs:
      - circle-node
      - circle-node-latest
      - circle-node-10
      - circle-node-9
      - circle-node-8
      - circle-node-7
      - bats
      - bats-latest
      - bats-1
      - zsh
      - zsh-latest
      - zsh-4
      - zsh-5
      - bash
      - bash-latest
      - bash-5
      - bash-4
      - bash-3

jobs:
  circle-node: &circle-node
    docker:
      - image: circleci/node
    steps:
      - checkout
      - env_info
      - run: |
          node --version
          npm --version
      - run: npm install npx bats
      - run: npx npx --version
      - run: npx bats --version
      - run: npx bats 'tests/main.bats'
  circle-node-latest: { <<: *circle-node, docker: [ image: circleci/node:latest ] }
  circle-node-10: { <<: *circle-node, docker: [ image: circleci/node:10 ] }
  circle-node-9: { <<: *circle-node, docker: [ image: circleci/node:9 ] }
  circle-node-8: { <<: *circle-node, docker: [ image: circleci/node:8 ] }
  circle-node-7: { <<: *circle-node, docker: [ image: circleci/node:7 ] }

  bats: &bats
    docker:
      - image: bats/bats
    steps:
      - checkout
      - env_info
      - run: bats --version
      - run: bats 'tests/main.bats'
  bats-latest: { <<: *bats, docker: [ image: bats/bats:latest ] }
  bats-1: { <<: *bats, docker: [ image: bats/bats:1 ] }

  zsh: &zsh
    docker:
      - image: zshusers/zsh
    steps:
      - checkout
      - env_info
      - run: zsh --version
      - run: zsh -c 'source home/shell/custom.zsh'
  zsh-latest: { <<: *zsh, docker: [ image: zshusers/zsh:latest ] }
  zsh-5: { <<: *zsh, docker: [ image: zshusers/zsh:5 ] }
  zsh-4: { <<: *zsh, docker: [ image: zshusers/zsh:4 ] }

  bash: &bash
    docker:
      - image: bash
    steps:
      - checkout
      - env_info
      - run: bash --version
      - run: bash -c 'source home/shell/custom.bash'
  bash-latest: { <<: *bash, docker: [ image: bash:latest ] }
  bash-5: { <<: *bash, docker: [ image: bash:5 ] }
  bash-4: { <<: *bash, docker: [ image: bash:4 ] }
  bash-3: { <<: *bash, docker: [ image: bash:3 ] }
