version: 2.1

commands:
  env_info:
    steps:
      - run:
          name: Print env info
          command: uname -a

workflows:
  version: 2
  test:
    jobs:
      - config-zsh
      - config-bash
      - install-apt
      - install-apt2
      - install-npm
      - install-pip
      - install-gem
      # TODO: add mac job

jobs:
  config-zsh:
    docker:
      - image: zshusers/zsh
    steps:
      - checkout
      - env_info
      - run: zsh --version
      - run: |
          zsh 'home/install.sh'
          zsh 'setup/install.sh'

  config-bash:
    docker:
      - image: bash
    steps:
      - checkout
      - env_info
      - run: bash --version
      - run: |
          bash 'home/install.sh'
          bash 'setup/install.sh'

  install-apt:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - env_info
      - run: apt-get update -y
      - run: sed -E 's~(\s*)#(.*)~~' <'dependencies/apt/apt.txt' | grep -vE '^(\s*)$' | xargs -tn1 apt-get install -y

  install-apt2:
    docker:
      - image: debian
    steps:
      - checkout
      - env_info
      - run: apt-get update -y
      - run: sed -E 's~(\s*)#(.*)~~' <'dependencies/apt/apt.txt' | grep -vE '^(\s*)$' | xargs -tn1 apt-get install -y

  install-npm:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - env_info
      - run: |
          node --version
          npm --version
      - run: node 'dependencies/npm/install.js'

  install-pip:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - env_info
      - run: |
          python --version
          pip --version
      - run: pip install --user -r 'dependencies/pip/requirements.txt'

  install-gem:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - env_info
      - run: |
          ruby --version
          gem --version
          bundle --version
      - run: bundle install --gemfile='dependencies/gem/Gemfile'
