version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - azlint
      - debian

jobs:
  azlint:
    docker:
      - image: matejkosiarcik/azlint
    steps:
      - checkout
      - setup_remote_docker
      - run: azlint

  debian:
    docker:
      - image: debian:stable
    steps:
      - checkout
      - run: make
