version: 2.1

commands:
  prepare:
    steps:
      - run:
          name: Update system package managers
          command: |
            if command -v apt-get >/dev/null 2>&1; then apt-get update; apt-get install --yes python3 python3-pip python3-venv python3-setuptools; fi
            if command -v apk >/dev/null 2>&1; then apk update --no-cache; apk add --no-cache python3 python3-dev py3-virtualenv; fi
            if command -v yum >/dev/null 2>&1; then command -v dnf >/dev/null 2>&1 || yum install -y dnf; fi
            if command -v dnf >/dev/null 2>&1; then dnf install -y make python3 python3-pip python3-setuptools; fi
workflows:
  version: 2
  test:
    jobs:
      - azlint
      - linux: { matrix: { parameters: { image: [ debian:stable, ubuntu:latest, ubuntu:rolling, elementary/docker:stable, alpine, fedora, centos ] }}}

jobs:
  azlint:
    docker:
      - image: matejkosiarcik/azlint
    steps:
      - checkout
      - setup_remote_docker
      - run: azlint

  linux:
    parameters:
      image:
        type: string
    docker:
      - image: "<< parameters.image >>"
    steps:
      - checkout
      - prepare
      - run: make
