name: Build and Test 🔧

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and Test 🔧
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [14, 15]
        python-version: [ 3.x', 'pypy-3.x' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4

      - name: Setup Python 🧩
        uses: actions/setup-python@v2.2.1
        with:
          python-version: python-version: ${{ matrix.python-version }}

      - name: Build and Test 🔧
        run: make
